# -*- mode: ruby -*-

ISO = "bento/ubuntu-20.04"
NET = "192.168.99."
DOMAIN = ".netology"
HOST_PREFIX = "server"
INVENTORY_PATH = "../ansible/inventory"

servers = [
  {
    :hostname => HOST_PREFIX + "1" + DOMAIN,
    :ip => NET + "11",
    :ssh_host => "20011",
    :ssh_vm => "22",
    :http_host => "8088",
    :http_vm => "8080",
    :elastic_p1_host => "9092",
    :elastic_p1_vm => "9200",
    :elastic_p2_host => "9093",
    :elastic_p2_vm => "9300",
    :ram => 1024,
    :core => 1
  }
]

Vagrant.configure(2) do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: false
  servers.each do |machine|
    config.vm.define machine[:hostname] do |node|
      node.vm.box = ISO
      node.vm.hostname = machine[:hostname]
      node.vm.network "private_network", ip: machine[:ip]
      node.vm.network :forwarded_port, guest: machine[:http_vm], host: machine[:http_host]
      node.vm.network :forwarded_port, guest: machine[:ssh_vm], host: machine[:ssh_host]
      node.vm.network :forwarded_port, guest: machine[:elastic_p1_vm], host: machine[:elastic_p1_host]
      node.vm.network :forwarded_port, guest: machine[:elastic_p2_vm], host: machine[:elastic_p2_host]
      node.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
        vb.customize ["modifyvm", :id, "--cpus", machine[:core]]
        vb.name = machine[:hostname]
      end
      node.vm.provision "ansible" do |setup|
        setup.inventory_path = INVENTORY_PATH
        setup.playbook = "../ansible/provision.yml"
        setup.become = true
        setup.verbose = ""
        setup.extra_vars = {
          ansible_user: 'vagrant',
          registry: 'https://index.docker.io/v1',
          username: 'bdvme',
          password: 'cdd01d0b-9524-41af-b26d-766caf8066fa'
        }
      end
    end
  end
end
