---
  - hosts: nodes
    become: yes
    become_user: root
    remote_user: vagrant
    roles:
      - ssh-keys
      - proxy_unset
      - check_dns
      - role: tools
        vars:
          tools_packages: ["python3", "python3-pip", "jq", "git", "wget", "curl", "unzip", "gnupg", "software-properties-common", "tor", "obfs4proxy", "ansible" ]
      - docker
      - sync
      - proxy_set
      - tor
      - reboot
      - role: sleep
        vars:
          count: "30"
      - check_ip
      - add_hashicorp
      - role: tools
        vars:
          tools_packages: ["terraform", "packer"]
      - terraform_init
      - proxy_unset
      - yc_init
      - yc_create_image
      - yc_create_infrastructure
      - ping_terraform_output
      - yc_delete_infrastructure
