{
 "title": "10.3 netology",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Memory free",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Disk free",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{fstype!~\"tmpfs|fuse.lxcfs|squashfs|vfat\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "CPU load average",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "node_load1{job=\"node\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "node_load5{job=\"node\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "node_load15{job=\"node\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "targets": [
    {
     "expr": "100 - (rate(node_cpu_seconds_total{job=\"node\", mode=\"idle\"}[1m]) * 100)",
     "legendFormat": "CPU{{cpu}}"
    }
   ]
  }
 ]
}