---
  - name: Add HashiCorp GPG key
    shell: curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
    environment: "{{ proxy_env }}"

  - name: Add HashiCorp linux repository
    shell: apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    environment: "{{ proxy_env }}"
