---
all:
  hosts:
    jenkins-master-01:
      ansible_host: 127.0.0.1
      ansible_port: 20011
      ssh_key_info:
        ssh_public_key: "~/.ssh/id_rsa.pub"
    jenkins-agent-01:
      ansible_host: 127.0.0.1
      ansible_port: 20012
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: vagrant

  #  ansible_ssh_user: vagrant
  #  ansible_python_interpreter: /usr/bin/python3
  #  ansible_ssh_pass: vagrant
  #  ansible_ssh_private_key_file: ~/.ssh/id_rsa
