---
  - name: Delete all on the Yandex Cloud
    command: "{{ item }}"
    with_items:
      - "bash erase.sh packer"
      - "bash erase.sh terraform"
    args:
      chdir: "/opt/packer"
    timeout: 3600
    ignore_errors: true
