---
  - hosts: nodes
    become: yes
    become_user: root
    remote_user: vagrant
    roles:
      - { role: ssh-keys, tags: "always" }
      - { role: check_dns, tags: "always" }
      - { role: proxy_unset, tags: "yc" }
      - { role: tools, vars: { tools_packages: ["python3",
                                                "python3-pip",
                                                "jq",
                                                "git",
                                                "wget",
                                                "curl",
                                                "unzip",
                                                "gnupg",
                                                "software-properties-common",
                                                "tor",
                                                "obfs4proxy",
                                                "ansible",
                                                "ansible-lint"] }, tags: ["yc","docker"] }
      - { role: sync, tags: "always" }
      - { role: docker, tags: "docker" }
      - { role: docker-compose, tags: "docker" }
      - { role: proxy_set, tags: "yc" }
      - { role: tor, tags: "yc" }
      - { role: reboot, tags: "yc" }
      - { role: sleep, vars: { count: "30" }, tags: "yc" }
      - { role: check_ip, tags: "yc" }
      - { role: add_hashicorp, tags: "yc" }
      - { role: tools, vars: { tools_packages: ["terraform", "packer"] }, tags: "yc" }
      - { role: proxy_unset, tags: "yc" }
      - { role: terraform_init, tags: "yc" }
      - { role: yc_init, tags: "yc" }
      - { role: yc_create_image, tags: "yc" }
      - { role: yc_create_infrastructure, tags: "yc" }
      - { role: sleep, vars: { count: "30" }, tags: "yc" }
      - { role: run_playbook, tags: ["yc", "docker"] }
      - { role: yc_delete_infrastructure, tags: "yc_destroy" }
      - { role: docker_prune, tags: "docker_destroy" }
