# -*- mode: ruby -*-

# ISO = "bento/ubuntu-20.04"
ISO = "centos/7"
NET = "192.168.99."
DOMAIN = ".netology"
HOST_PREFIX = "server"
INVENTORY_PATH = "../ansible/inventory"

servers = [
  {
    :hostname => HOST_PREFIX + "01" + DOMAIN,
    :ip => NET + "101",
    :ssh_host => "20101",
    :ssh_vm => "22",
    :ram => 1024,
    :core => 1,
    :tags => "",
    :verbose => "true"
  },
  {
    :hostname => HOST_PREFIX + "02" + DOMAIN,
    :ip => NET + "102",
    :ssh_host => "20102",
    :ssh_vm => "22",
    :ram => 1024,
    :core => 1,
    :tags => "",
    :verbose => "false"
  },
  {
    :hostname => HOST_PREFIX + "03" + DOMAIN,
    :ip => NET + "103",
    :ssh_host => "20103",
    :ssh_vm => "22",
    :ram => 1024,
    :core => 1,
    :tags => "",
    :verbose => "false"
  },
  {
    :hostname => HOST_PREFIX + "04" + DOMAIN,
    :ip => NET + "104",
    :ssh_host => "20104",
    :ssh_vm => "22",
    :ram => 1024,
    :core => 1,
    :tags => "master",
    :verbose => "false"
  }
]

Vagrant.configure(2) do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: false
  config.ssh.insert_key = false
  config.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
  config.ssh.forward_agent = true
  servers.each do |machine|
    config.vm.define machine[:hostname] do |node|
      node.vm.box = ISO
      node.vm.hostname = machine[:hostname]
      node.vm.network "private_network", ip: machine[:ip]
      node.vm.network :forwarded_port, guest: machine[:ssh_vm], host: machine[:ssh_host]
      node.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
        vb.customize ["modifyvm", :id, "--cpus", machine[:core]]
        vb.name = machine[:hostname]
      end
      node.vm.provision "ansible" do |setup|
        setup.inventory_path = INVENTORY_PATH
        setup.playbook = "../ansible/provision.yml"
        setup.tags=machine[:tags]
        setup.become = true
      end
    end
  end
end
