---
  - name: Get image-id
    command: "yc compute image list --format yaml"
    register: image_id

  - name: Grep variable
    shell:
      cmd: "echo {{ image_id.stdout_lines[0]}} | awk '{print $3}'"
    register: image_id

  - name: Set variable yandex_image_id
    set_fact:
      yandex_image_id: "{{ image_id.stdout }}"

  - name: Create infrastructure
    command: terraform apply -auto-approve \
                           -var="yandex_folder_id={{ yandex_folder_id }}" \
                           -var="yandex_cloud_id={{ yandex_cloud_id }}" \
                           -var="yandex_image_id={{ yandex_image_id }}"
    args:
      chdir: "/opt/terraform"
    environment: "{{ yc_env }}"
    timeout: 3600
    ignore_errors: true
