---

  - hosts: nodes
    become: yes
    become_user: root
    remote_user: vagrant
    vars_prompt:
      - name: registry
        prompt: "Registry"
        private: no
        default: "https://index.docker.io/v1"
      - name: username
        prompt: "Username"
        private: no
        default: "username"
      - name: password
        prompt: "Password"
        default: "token"
    tasks:
      - name: Create directory for ssh-keys
        file: state=directory mode=0700 dest=/root/.ssh/

      - name: Adding rsa-key in /root/.ssh/authorized_keys
        copy: src=~/.ssh/id_rsa.pub dest=/root/.ssh/authorized_keys owner=root mode=0600
        ignore_errors: yes

      - name: Installing tools
        apt: >
          package={{ item }}
          state=present
          update_cache=yes
        with_items:
          - git
          - curl
          - python3
          - python3-pip

      - name: Installing docker
        shell: |
          curl -fsSL get.docker.com -o get-docker.sh
          chmod +x get-docker.sh
          ./get-docker.sh

      - name: Add the current user to docker group
        user: name=vagrant append=yes groups=docker

      - name: Create directory
        file:
          path=./docker_nginx
          state=directory
          mode=0755

      - name: Copy files for webserver
        copy:
          src: "../webserver/{{ item }}"
          dest: "./docker_nginx"
        with_items:
          - "index.html"
          - "Dockerfile"

      - name: Install docker.py
        pip:
          name: docker
          state: present

      - name: Start docker service
        service:
          name: docker
          state: restarted
          enabled: yes

      - name: Docker login
        docker_login:
          registry: "{{ registry }}"
          username: "{{ username }}"
          password: "{{ password }}"

      - name: Build docker image
        docker_image:
          name: webserver:latest
          repository: bdvme/devtest
          source: build
          push: yes
          build:
            dockerfile: Dockerfile
            path: "./docker_nginx"
          tag: v1.0
          state: present

      - name: Restart a container
        docker_container:
          name: webserver
          image: bdvme/devtest
          state: started
          restart: yes
          ports:
            - "8080:80"
