---
  - hosts: nodes
    become: yes
    become_user: root
    remote_user: vagrant
    roles:
      - ssh-keys
      - check_dns
      - role: tools
        vars:
          tools_packages: ["python3", "python3-pip", "git", "wget", "curl", "ansible", "ansible-lint" ]
#      - docker
      - sync
#      - docker-compose
