---

  - hosts: nodes
    become: yes
    become_user: root
    remote_user: vagrant
    vars:
      proxy_env:
        http_proxy: socks5://127.0.0.1:9050
        https_proxy: socks5://127.0.0.1:9050
      yc_env:
        yandex_token: "token"
        yandex_zone: "zone"
        yandex_cloud_id: "cloud-id"
        yandex_folder_id: "folder-id"
        yandex_image_id: "image-id"
        yandex_service_acc: "service_acc"
        yandex_service_acc_id: "service_acc-id"
        yandex_profile: "profile01"
        yandex_external_ip_address: "127.0.0.1"

    tasks:
      - name: Create directory for ssh-keys
        file: state=directory mode=0700 dest=/root/.ssh/

      - name: Adding rsa-key in /root/.ssh/authorized_keys
        copy: src=~/.ssh/id_rsa.pub dest=/root/.ssh/authorized_keys owner=root mode=0600
        ignore_errors: yes

      - name: Adding rsa-key in /root/.ssh
        command: "{{ item }}"
        with_items:
          - "rm -rf /root/.ssh"
          - "ssh-keygen -q -t rsa -N '' -f /root/.ssh/id_rsa"
        ignore_errors: yes

      - name: Clear /etc/apt/apt.conf.d/01proxy file
        shell: "echo > /etc/apt/apt.conf.d/01proxy"

      - name: Set default state /etc/apt/sources.list
        copy:
          src: stack/etc/apt/sources.list
          dest: /etc/apt/
          owner: root
          group: root
          mode: 0644
        become: true

      - name: Checking DNS
        command: host -t A google.com

      - name: Installing tools
        apt: >
          package={{ item }}
          state=present
          update_cache=yes
        with_items:
          - git
          - unzip
          - curl
          - gnupg
          - software-properties-common
          - tor
          - obfs4proxy
          - jq
          - ansible

      - name: Synchronization
        copy:
          src: stack/
          dest: "/"
          owner: root
          group: root
          mode: 0644
        become: true

      - name: Enable Tor network
        command: "{{ item }}"
        with_items:
          - "systemctl enable tor"
        environment: "{{ proxy_env }}"
        register: shell_output

      - name: Reboot host and wait for it to restart
        reboot:
          msg: "Reboot initiated by Ansible"
          connect_timeout: 5
          reboot_timeout: 600
          pre_reboot_delay: 0
          post_reboot_delay: 30
          test_command: whoami

      - name: Checking IP
        command: "{{ item }}"
        with_items:
          - "curl ifconfig.me"
        environment: "{{ proxy_env }}"
        register: shell_output

      - debug: "var=shell_output.stdout_lines"

      - name: Add HashiCorp GPG key
        shell: curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
        environment: "{{ proxy_env }}"

      - name: Add HashiCorp linux repository
        shell: apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        environment: "{{ proxy_env }}"

      - name: Installing tools
        apt: >
          package={{ item }}
          state=present
          update_cache=yes
        with_items:
          - terraform
          - packer
        environment: "{{ proxy_env }}"
        timeout: 3600

      - name: Install Yandex Cloud
        command: "{{ item }}"
        with_items:
          - "curl -s -O https://storage.yandexcloud.net/yandexcloud-yc/install.sh"
          - "chmod u+x install.sh"
          - "sudo ./install.sh -a -i /usr/local/ 2>/dev/null"
          - "rm -rf install.sh"
          - "sudo sed -i '$ a source /usr/local/completion.bash.inc' /etc/profile"
        args:
          chdir: "/opt/"
        timeout: 3600

      - name: Terraform initialize
        command: "terraform init -force-copy"
        args:
          chdir: "/opt/terraform"
        environment: "{{ proxy_env }}"

      - name: Yandex Cloud set profile
        command: "{{ item }}"
        with_items:
          - "yc config profile create {{ yandex_profile }}"
          - "yc config set folder-id {{ yandex_folder_id }}"
          - "yc config set cloud-id {{ yandex_cloud_id }}"
          - "yc config set token {{ yandex_token }}"
          - "yc config set compute-default-zone {{ yandex_zone }}"
          - "yc config profile activate {{ yandex_profile }}"
        environment: "{{ yc_env }}"
        ignore_errors: true
        no_log: true

      - name: Create Yandex Cloud service account
        command: "yc iam service-account create --name {{ yandex_service_acc }}"
        ignore_errors: true

      - name: Get service_acc-id
        command: "yc iam service-account get {{ yandex_service_acc }}"
        register: service_acc

      - name: Grep variable
        shell:
          cmd: "echo {{ service_acc.stdout_lines[0]}} | awk '{print $2}'"
        register: service_acc

      - name: Set variable yandex_service_acc_id
        set_fact:
          yandex_service_acc_id: "{{ service_acc.stdout }}"

      - name: Set Editor role to Yandex Cloud service account
        command: "yc resource-manager folder add-access-binding my-folder \
         --role editor \
         --subject serviceAccount:{{ yandex_service_acc_id }}"

      - name: Create Yandex Cloud key.json
        command: "{{ item }}"
        with_items:
          - "rm -rf key.json"
          - "yc iam key create --service-account-name {{ yandex_service_acc }} --output key.json"
          - "yc config set service-account-key key.json"
          - "yc config set token {{ yandex_token }}"
        args:
          chdir: "/opt/terraform"
        ignore_errors: true
        no_log: true

      - name: Create image on the Yandex Cloud
        command: "bash create_image.sh"
        args:
          chdir: "/opt/packer"
        timeout: 3600
        ignore_errors: true

      - name: Get image-id
        command: "yc compute image list --format yaml"
        register: image_id

      - name: Grep variable
        shell:
          cmd: "echo {{ image_id.stdout_lines[0]}} | awk '{print $3}'"
        register: image_id

      - name: Set variable yandex_image_id
        set_fact:
          yandex_image_id: "{{ image_id.stdout }}"

      - name: Create infrastructure
        command: terraform apply -auto-approve \
                               -var="yandex_folder_id={{ yandex_folder_id }}" \
                               -var="yandex_cloud_id={{ yandex_cloud_id }}" \
                               -var="yandex_image_id={{ yandex_image_id }}"
        args:
          chdir: "/opt/terraform"
        environment: "{{ yc_env }}"
        timeout: 3600
        ignore_errors: true

      - slurp:
          path: "/opt/terraform/yc_external_ip.yml"
        register: yc_external_ip

      - name: Get external_ip
        set_fact:
          input: "{{ (yc_external_ip.content|b64decode|from_json).node01_netology_yc }}"

      - debug:
          msg: "{{ input }}"

      - name: Set variable yandex_external_ip_address
        set_fact:
          yandex_external_ip_address: "{{ input }}"

      - name: Ping yandex_external_ip_address
        command: "{{ item }}"
        with_items:
          - "ping -c 20 {{ yandex_external_ip_address }}"

      - name: Delete all on the Yandex Cloud
        command: "{{ item }}"
        with_items:
          - "bash erase.sh packer"
          - "bash erase.sh terraform"
        args:
          chdir: "/opt/packer"
        timeout: 3600
