---
  - name: Create directory for ssh-keys
    file: state=directory mode=0700 dest=/root/.ssh/

  - name: Adding rsa-key in /root/.ssh/authorized_keys
    copy: src=~/.ssh/id_rsa.pub dest=/root/.ssh/authorized_keys owner=root mode=0600
    ignore_errors: yes

  - name: Adding rsa-key in /root/.ssh
    command: "{{ item }}"
    with_items:
      - "rm -rf /root/.ssh"
      - "ssh-keygen -q -t rsa -N '' -f /root/.ssh/id_rsa"
    ignore_errors: yes
