FROM centos/systemd
ENV container docker

RUN yum -y update && \
yum -y install yum -y install bridge-utils bind-utils iptables curl net-tools tcpdump rsync telnet openssh-server python3 python3-pip sudo

VOLUME [ "/sys/fs/cgroup" ]
CMD ["/usr/sbin/init"]
