#cloud-config
users:
  - name: ${username}
    ssh-authorized-keys:
      - ${ssh_public_key}
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash

write_files:
  - content: |
      ${contents}
    path: "/var/www/html/index.html"
    owner: root:root
    permissions: "0664"