---
all:
  hosts:
    jenkins-master-01:
      ansible_host: 192.168.99.11
      ssh_key_info:
        ssh_public_key: "~/.ssh/id_rsa.pub"
      ansible_python_interpreter: "/usr/bin/python2"
    jenkins-agent-01:
      ansible_host: 192.168.99.12
      ssh_key_info:
        ssh_public_key: "~/.ssh/id_rsa.pub"
      ansible_python_interpreter: "/usr/bin/python3"
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: vagrant
