---
  - name: Run requirements.yml
    become: yes
    command: ansible-galaxy install -f -r requirements.yml --roles-path roles --ignore-errors
    args:
      chdir: "/opt/playbook"
  - name: Run ansible-playbook
    command: ansible-playbook -i ./inventory/prod.yml playbook.yml
    args:
      chdir: "/opt/playbook"
