apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: busybox
          image: busybox
          command:
            - "/bin/sh"
            - "-c"
            - "while true; do echo 'Hello Netology!' >> /msg-out-path/test; sleep 5; done"
          volumeMounts:
            - mountPath: /msg-out-path
              name: msg-volume
        - name: multitool
          image: wbitt/network-multitool
          volumeMounts:
            - mountPath: /msg-in-path
              name: msg-volume
      volumes:
        - emptyDir: {}
          name: msg-volume            