stages:
  - build
  - deploy
image: docker:20.10.16
variables:
  DOCKER_TLS_CERTDIR: ""
services:
  - docker:20.10.16-dind
builder:
  stage: build
  script:
    - docker build -t python-api:latest ./app
  except:
    - main
    - master
deployer:
  stage: deploy
  script:
    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH/python-api:latest ./app
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH/python-api:latest
  only:
    - main
    - master