apiVersion: v1
kind: Service
metadata:
  name: auth-db
  namespace: web
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: ExternalName
  externalName: auth-db.data.svc.cluster.local