version: "3.3"
services:
  clickhouse:
    build:
      context: .
      dockerfile: dockerfile_clickhouse
    container_name: clickhouse-01
    stdin_open: true
    tty: true
    entrypoint: /bin/bash
  vector:
    build:
      context: .
      dockerfile: dockerfile_vector
    container_name: vector-01
    stdin_open: true
    tty: true
    entrypoint: /bin/bash
