version: "3.3"
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwertyui"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./backups:/var/lib/postgresql/backups
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
